name: publish
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi Mom"
      - run: echo ${{secrets.DEPLOY_TOKEN}}
      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

  trigger_deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment
        id: create_deployment
        uses: octokit/request-action@v2.1.9
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          description: "Deploy triggered by GitHub Actions"
          environment: dev
          payload: |
            aws_account: rl-internal
          ref: ${{ github.sha }}
          task: deploy
          required_contexts: "['test']"
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
